# Generated by Django 5.2.16 on 2026-07-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("organization", models.CharField(max_length=150)),
                (
                    "date_range",
                    models.CharField(
                        help_text="e.g., Summer 2026 or June 2026 - Present",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Check if this is your current role"
                    ),
                ),
            ],
        ),
    ]
