# Generated by Django 5.2.16 on 2026-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0002_contactmessage_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="live_link",
            field=models.URLField(
                blank=True, help_text="Link to the deployed live project", null=True
            ),
        ),
    ]
