# Generated by Django 5.2.16 on 2026-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0004_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(
                related_name="projects", to="Portfolio.category"
            ),
        ),
    ]
